# Node.js with Grunt
# Build a Node.js project using the Grunt task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    
  displayName: 'npm install and run grunt'

- task: BatchScript@1
  inputs:
    filename: run/runTestsOnLocal.bat
    command: run/runTestsOnLocal.bat
    customCommand: 'run/runTestsOnLocal.bat'
