
# Node.js with Grunt
# Build a Node.js project using the Grunt task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'


- script: |
    node --version
    npm install
    npm install -g grunt-cli
    npm install grunt-cli
    npm install grunt --save-dev
  displayName: 'npm install and run grunt'
   

- script: |
    npm install webdriver-manager -g
    npm install protractor -g
    webdriver-manager update
    webdriver-manager start
  displayName: 'Webdriver install'


-  task: CmdLine@2
   inputs:
    script: |         
      cd resources
      grunt
   

